### ISSUE TITLE
setting starting folder manually

### ISSUE THREAD

**Issue by larshp** [grahamrobbo/building_gateway_services#1]
Hi,
It should work without setting the starting folder to /src/ manually, have you tried without the step?

https://github.com/grahamrobbo/building_gateway_services/blob/master/docs/README.md

**Comment by grahamrobbo** [comment]
Really? So it overwrites local .abapgit.xml file with one from remote? No I haven't tried it - but will.

**Comment by grahamrobbo** [comment]
Yep - all good. Makes sense as I am pulling not pushing. 
![image](https://user-images.githubusercontent.com/1305633/29150202-5517abce-7dbc-11e7-866e-fb58866d5e6f.png)
